[framework]
name = "perfect"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Realistic"
classification = "Micro"
database = "None"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "Perfect"
webserver = "Perfect"

[mongodb]
urls.db = "/db"
urls.query = "/queries?queries="
urls.update = "/updates?queries="
approach = "Realistic"
classification = "Micro"
database = "MongoDB"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "Perfect"
webserver = "Perfect"

[postgresql]
urls.db = "/db"
urls.query = "/queries?queries="
urls.update = "/updates?queries="
approach = "Realistic"
classification = "Micro"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "Perfect"
webserver = "Perfect"

[mysql]
urls.db = "/db"
urls.query = "/queries?queries="
urls.update = "/updates?queries="
approach = "Realistic"
classification = "Micro"
database = "MySQL"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "Perfect"
webserver = "Perfect"
