[framework]
name = "rack"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
urls.db = "/db"
urls.query = "/queries?queries="
urls.update = "/updates?queries="
approach = "Stripped"
classification = "Platform"
database = "MySQL"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "Rack"
webserver = "Puma"

[falcon]
urls.plaintext = "/plaintext"
urls.json = "/json"
urls.db = "/db"
urls.query = "/queries?queries="
urls.update = "/updates?queries="
approach = "Stripped"
classification = "Platform"
database = "MySQL"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "Rack"
webserver = "Falcon"

[unicorn]
urls.plaintext = "/plaintext"
urls.json = "/json"
urls.db = "/db"
urls.query = "/queries?queries="
urls.update = "/updates?queries="
approach = "Stripped"
classification = "Platform"
database = "MySQL"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "Rack"
webserver = "Unicorn"
