[framework]
name = "kitura"

[postgres-orm]
urls.db = "/db"
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Fullstack"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Full"
platform = "KituraNet"
webserver = "Kitura"

[gcd-postgres-orm-codable]
urls.db = "/db"
approach = "Realistic"
classification = "Fullstack"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Full"
platform = "KituraNet"
webserver = "Kitura"

[gcd]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Realistic"
classification = "Fullstack"
database = "none"
database_os = "Linux"
os = "Linux"
orm = "none"
platform = "KituraNet"
webserver = "Kitura"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Realistic"
classification = "Fullstack"
database = "none"
database_os = "Linux"
os = "Linux"
orm = "none"
platform = "KituraNet"
webserver = "Kitura"

[mongodb]
urls.db = "/db"
urls.query = "/queries?queries="
urls.update = "/updates?queries="
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Fullstack"
database = "MongoDB"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "KituraNet"
webserver = "Kitura"

[nio]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Realistic"
classification = "Fullstack"
database = "none"
database_os = "Linux"
os = "Linux"
orm = "none"
platform = "KituraNIO"
webserver = "Kitura"

[gcd-postgres-orm]
urls.db = "/db"
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Fullstack"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Full"
platform = "KituraNet"
webserver = "Kitura"

[nio-postgres-orm]
urls.db = "/db"
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Fullstack"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Full"
platform = "KituraNIO"
webserver = "Kitura"

[nio-postgres]
urls.db = "/db"
urls.query = "/queries?queries="
urls.update = "/updates?queries="
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Fullstack"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "KituraNIO"
webserver = "Kitura"

[postgres-orm-codable]
urls.db = "/db"
urls.query = "/queries?queries="
urls.update = "/updates?queries="
approach = "Realistic"
classification = "Fullstack"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Full"
platform = "KituraNet"
webserver = "Kitura"

[nio-postgres-orm-codable]
urls.db = "/db"
urls.query = "/queries?queries="
urls.update = "/updates?queries="
approach = "Realistic"
classification = "Fullstack"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Full"
platform = "KituraNIO"
webserver = "Kitura"

[gcd-postgres]
urls.db = "/db"
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Fullstack"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "KituraNet"
webserver = "Kitura"

[postgres]
urls.db = "/db"
urls.query = "/queries?queries="
urls.update = "/updates?queries="
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Fullstack"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "KituraNet"
webserver = "Kitura"
